// Ergast returns nationality as a demonym ("British", "German"). Map the
// common F1 nationalities to a flag emoji for compact display.

const NATIONALITY_FLAG = {
  British: '🇬🇧',
  English: '🇬🇧',
  Scottish: '🇬🇧',
  Welsh: '🇬🇧',
  'Northern Irish': '🇬🇧',
  German: '🇩🇪',
  'East German': '🇩🇪',
  Italian: '🇮🇹',
  French: '🇫🇷',
  Monegasque: '🇲🇨',
  Spanish: '🇪🇸',
  Dutch: '🇳🇱',
  Finnish: '🇫🇮',
  Brazilian: '🇧🇷',
  Argentine: '🇦🇷',
  American: '🇺🇸',
  'American-Italian': '🇺🇸',
  Australian: '🇦🇺',
  Austrian: '🇦🇹',
  Belgian: '🇧🇪',
  Canadian: '🇨🇦',
  Mexican: '🇲🇽',
  Japanese: '🇯🇵',
  'New Zealander': '🇳🇿',
  Swiss: '🇨🇭',
  Swedish: '🇸🇪',
  Danish: '🇩🇰',
  Portuguese: '🇵🇹',
  'South African': '🇿🇦',
  Russian: '🇷🇺',
  Polish: '🇵🇱',
  Thai: '🇹🇭',
  Chinese: '🇨🇳',
  Colombian: '🇨🇴',
  Venezuelan: '🇻🇪',
  Indian: '🇮🇳',
  Indonesian: '🇮🇩',
  Malaysian: '🇲🇾',
  Hungarian: '🇭🇺',
  Czech: '🇨🇿',
  Irish: '🇮🇪',
  Uruguayan: '🇺🇾',
  Chilean: '🇨🇱',
  Liechtensteiner: '🇱🇮',
  Rhodesian: '🇿🇼',
}

export function flag(nationality) {
  return NATIONALITY_FLAG[nationality] || '🏁'
}
